services:
  - type: web
    name: notes-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./notes.db
